# Generated by Django 5.0.6 on 2024-06-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_prayerrequest_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
