# Generated by Django 5.0.6 on 2024-07-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_prayerrequest_group'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerrequest',
            name='group',
        ),
        migrations.CreateModel(
            name='GroupPrayerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prayerrequest')),
            ],
        ),
    ]
