# Generated by Django 5.0.6 on 2024-07-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_prayerrequest_group_groupprayermanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prayerrequest')),
            ],
        ),
    ]
